// Données mockées basées sur le fichier CSV
export const artisansData = [
    {
        id: 1,
        nom: "Boucherie Dumont",
        specialite: "Boucher",
        note: 4.5,
        ville: "Lyon",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "boucherie.dumond@gmail.com",
        siteWeb: "",
        categorie: "Alimentation",
        top: false
    },
    {
        id: 2,
        nom: "Au pain chaud",
        specialite: "Boulanger",
        note: 4.8,
        ville: "Montélimar",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "aupainchaud@hotmail.com",
        siteWeb: "",
        categorie: "Alimentation",
        top: true
    },
    {
        id: 3,
        nom: "Chocolaterie Labbé",
        specialite: "Chocolatier",
        note: 4.9,
        ville: "Lyon",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "chocolaterie-labbe@gmail.com",
        siteWeb: "https://chocolaterie-labbe.fr",
        categorie: "Alimentation",
        top: true
    },
    {
        id: 4,
        nom: "Traiteur Truchon",
        specialite: "Traiteur",
        note: 4.1,
        ville: "Lyon",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "contact@truchon-traiteur.fr",
        siteWeb: "https://truchon-traiteur.fr",
        categorie: "Alimentation",
        top: false
    },
    {
        id: 5,
        nom: "Orville Salmons",
        specialite: "Chauffagiste",
        note: 5.0,
        ville: "Evian",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "o-salmons@live.com",
        siteWeb: "",
        categorie: "Bâtiment",
        top: true
    },
    {
        id: 6,
        nom: "Mont Blanc Eléctricité",
        specialite: "Electricien",
        note: 4.5,
        ville: "Chamonix",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "contact@mont-blanc-electricite.com",
        siteWeb: "https://mont-blanc-electricite.com",
        categorie: "Bâtiment",
        top: false
    },
    {
        id: 7,
        nom: "Boutot & fils",
        specialite: "Menuisier",
        note: 4.7,
        ville: "Bourg-en-bresse",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "boutot-menuiserie@gmail.com",
        siteWeb: "https://boutot-menuiserie.com",
        categorie: "Bâtiment",
        top: false
    },
    {
        id: 8,
        nom: "Vallis Bellemare",
        specialite: "Plombier",
        note: 4.0,
        ville: "Vienne",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "v.bellemare@gmail.com",
        siteWeb: "https://plomberie-bellemare.com",
        categorie: "Bâtiment",
        top: false
    },
    {
        id: 9,
        nom: "Claude Quinn",
        specialite: "Bijoutier",
        note: 4.2,
        ville: "Aix-les-bains",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "claude.quinn@gmail.com",
        siteWeb: "",
        categorie: "Fabrication",
        top: false
    },
    {
        id: 10,
        nom: "Amitee Lécuyer",
        specialite: "Couturier",
        note: 4.5,
        ville: "Annecy",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "a.amitee@hotmail.com",
        siteWeb: "https://lecuyer-couture.com",
        categorie: "Fabrication",
        top: false
    },
    {
        id: 11,
        nom: "Ernest Carignan",
        specialite: "Ferronier",
        note: 5.0,
        ville: "Le Puy-en-Velay",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "e-carigan@hotmail.com",
        siteWeb: "",
        categorie: "Fabrication",
        top: false
    },
    {
        id: 12,
        nom: "Royden Charbonneau",
        specialite: "Coiffeur",
        note: 3.8,
        ville: "Saint-Priest",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "r.charbonneau@gmail.com",
        siteWeb: "",
        categorie: "Services",
        top: false
    },
    {
        id: 13,
        nom: "Leala Dennis",
        specialite: "Coiffeur",
        note: 3.8,
        ville: "Chambéry",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "l.dennos@hotmail.fr",
        siteWeb: "https://coiffure-leala-chambery.fr",
        categorie: "Services",
        top: false
    },
    {
        id: 14,
        nom: "C'est sup'hair",
        specialite: "Coiffeur",
        note: 4.1,
        ville: "Romans-sur-Isère",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "sup-hair@gmail.com",
        siteWeb: "https://sup-hair.fr",
        categorie: "Services",
        top: false
    },
    {
        id: 15,
        nom: "Le monde des fleurs",
        specialite: "Fleuriste",
        note: 4.6,
        ville: "Annonay",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "contact@le-monde-des-fleurs-annonay.fr",
        siteWeb: "https://le-monde-des-fleurs-annonay.fr",
        categorie: "Services",
        top: false
    },
    {
        id: 16,
        nom: "Valérie Laderoute",
        specialite: "Toiletteur",
        note: 4.5,
        ville: "Valence",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "v-laredoute@gmail.com",
        siteWeb: "",
        categorie: "Services",
        top: false
    },
    {
        id: 17,
        nom: "CM Graphisme",
        specialite: "Webdesign",
        note: 4.4,
        ville: "Valence",
        aPropos: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus eleifend ante sem, id volutpat massa fermentum nec. Praesent volutpat scelerisque mauris, quis sollicitudin tellus sollicitudin.",
        email: "contact@cm-graphisme.com",
        siteWeb: "https://cm-graphisme.com",
        categorie: "Services",
        top: false
    }
]; 